# Generated by Django 5.2.2 on 2025-06-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimplexProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optim', models.CharField(choices=[('max', 'Maximizar'), ('min', 'Minimizar')], max_length=3)),
                ('n', models.PositiveIntegerField()),
                ('m', models.PositiveIntegerField()),
                ('obj', models.CharField(max_length=255)),
                ('cons', models.TextField()),
                ('types', models.CharField(max_length=255)),
                ('rhs', models.CharField(max_length=255)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
