# Generated by Django 5.2.2 on 2025-07-02 03:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='perfil/usuario.png', upload_to='perfil/')),
                ('telefono', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')])),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
