# Generated by Django 5.2.2 on 2025-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_ciudad_perfilusuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='ciudad',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(default='perfil/usuario.png', upload_to='perfil/'),
        ),
    ]
