# Generated by Django 5.2.2 on 2025-06-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_ciudad_perfilusuario_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='apellido',
            new_name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nombre',
        ),
    ]
