# Generated by Django 5.2.2 on 2025-06-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_apellido_perfilusuario_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
    ]
