# Generated by Django 5.2.2 on 2025-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfilusuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
