# Generated by Django 5.2.2 on 2025-07-01 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
    ]
