# Generated by Django 5.2.2 on 2025-07-02 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optim', models.CharField(choices=[('max', 'Maximizar'), ('min', 'Minimizar')], max_length=3)),
                ('n', models.PositiveIntegerField()),
                ('m', models.PositiveIntegerField()),
                ('obj', models.CharField(max_length=100)),
                ('cons', models.TextField(default='')),
                ('types', models.CharField(max_length=100)),
                ('rhs', models.CharField(max_length=100)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_grafico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
