# Generated by Django 5.2.2 on 2025-07-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('restricciones', models.TextField(help_text='JSON serializado de restricciones')),
                ('funcion_objetivo', models.CharField(max_length=255)),
                ('solucion_optima', models.JSONField(blank=True, null=True)),
                ('vertices_factibles', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
